export default interface PatientInfoParamsInterface{
    patient_id : string,
    patient_fname : string ,
    patient_mname : string,
    patient_lname : string ,
    patient_date_assess : Date ,
    patient_age INT ,
    patient_sex : string ,
    patient_dob : Date ,
    patient_civil_status: string ,
    patient_religion : string,
    patient_contact_no : string,
    patient_street : string,
    patient_purok : string,
    patient_sitio : string,
    patient_brgy : string,
    patient_muncity : string,
    patient_province : string,
    patient_phic_no : string,
    patient_pwd_no : string,
    patient_emp_status : string,
    patient_ip : string,
    patient_ip_ethinicity : string,
    hf_id : string,

}