enum TableNames {
  // Primary tables
  RELIGION_TABLE = "a_religion",
  ETHNICITY_TABLE = "a_ethnicity",
  BARANGAY_TABLE = "a_brgy_info",
  SUPERADMIN_INFO_TABLE = "a_superadmin_info",
  SUPERVISOR_INFO_TABLE = "a_supervisor_info",
  OFFICER_INFO_TABLE = "a_officer_info",
  CONSULTATION_LOGS_TABLE = "a_consultation_logs",
  HEALTH_FACILITY_INFO_TABLE = "a_health_facility_info",
  PATIENT_INFO_TABLE = "a_patient_info",
  AGE_GROUP_TABLE = "a_age_group",
  ASSESS_RED_FLAG_TABLE = "a_assess_red_flags",
  ASSESS_RED_FLAG_SUMMARY_TABLE = "a_ard_summary",
  PAST_MEDICAL_HISTORY_TABLE = "a_past_medical_history",
  FAMILY_HISTORY_TABLE = "a_family_history",
  NCD_RISK_FACTORS_TABLE = "a_ncd_risk_factors",
  RISK_SCREENING_TABLE = "a_risk_screening",
  MANAGEMENT_TABLE = "a_management",
  REFERRAL_TABLE = "a_referral",
  MUNCITY_TABLE = "a_muncity_info",
  PROVINCE_TABLE = "a_province_info",

  // Default tables
  AGE_BRACKET = "age_bracket",
  AVAILABLE_SERVICES = "available_services",
  BRACKET_SERVICES = "bracket_services",
  CASES = "cases",
  FEEDBACK = "feedback",
  GENERAL_INFORMATION = "general_information",
  IMMUSTAT = "immu_stat",
  MEDICATION = "medication",
  PHIC_MEMBERSHIP = "phic_membership",
  PROFILE = "profile",
  SERVICES = "services",
  TUBERCULOSIS = "tuberculosis",
}

export default TableNames;
